### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Dream-Master** [Vexatos/TinkersGregworks#10]
How i make tool parts that not have any Ingots like Sealed wood.

**Comment by Dream-Master** [comment]
This Questions come because i want to make the Recipes in Minetweaker (for tinkers wood tools in the Gt machines) and looking for some equivalent materials to compare the eu consumption.

**Comment by Dream-Master** [comment]
Thaumium is allready inside tinkers construct.

**Comment by Vexatos** [comment]
...I have no idea what you mean, I'm afraid.

**Comment by Dream-Master** [comment]
Ok my question is how you can make sealed wood tool parts? The Extruder accept only the ingots and sealed wood not have ingots.

**Comment by Vexatos** [comment]
Well, then there is no way of creating them. All recipes and tool parts are generated dynamically. I won't add manual recipes for special cases like this.
