### ISSUE TITLE
Need Tinkers Build 977

### ISSUE THREAD

**Issue by Dream-Master** [Vexatos/TinkersGregworks#12]
For those they don't know where tinkers have the jenkins to get build 977 or compile the code comletly maybe downgrade to 1.8.6b. I see you make the last commit on tinkers but boni not make a new Version of TC.
(btw i using Version 977 so its not an issue for me)

**Comment by Vexatos** [comment]
To keep things short: This mod crashes when a build below 977 is being used (When opening the creative search tab). That's just the way it is.

**Comment by Dream-Master** [comment]
Ok.
