### ISSUE TITLE
Mattok not craftable

### ISSUE THREAD

**Issue by Dream-Master** [Vexatos/TinkersGregworks#14]
@Vexatos 
I try to craft a mattock out of Neutronium, Osmium, Iridium and Stainless Steel but it  dont let me craft one.

**Comment by Dream-Master** [comment]
Mattok not works with version 1.0.7 too.

**Comment by Vexatos** [comment]
Thanks for the report! Please re-download 1.0.7 from [here](http://files.vex.tty.sh/TGregworks/) for a fixed build.

**Comment by Dream-Master** [comment]
Thanks. :+1:
