### ISSUE TITLE
GemBlocks processing for tool parts

### ISSUE THREAD

**Issue by deeplyarnab** [Vexatos/TinkersGregworks#16]
Is there currently a way to use the gem stuff to be used for making tool parts? I tried making pickaxe heads from Amber(thaumcraft) & Amethyst(gregtech) but both didn't work with part builder either (nor with extruders)

**Comment by Vexatos** [comment]
Can you make normal GregTech tools with those (i.e. a GregTech Saw Blade made of Amber)? TGregworks only adds tools for materials that GregTech tools can be made of.

**Comment by arnabbiswasalsodeep** [comment]
yes for amber, no for amethyst

**Comment by arnabbiswasalsodeep** [comment]
No, saws don't have a recipe, but we can make axe head and stuff from it

**Comment by Vexatos** [comment]
I will look into it.

**Comment by Vexatos** [comment]
Should be in version 1.0.9 of TGregworks. Go give it a try.

**Comment by deeplyarnab** [comment]
Thank you! :D
