### ISSUE TITLE
[Suggestion] Alternate Fluid Solidifier Recipes

### ISSUE THREAD

**Issue by Muramasa-** [Vexatos/TinkersGregworks#17]
Would it be possible to add alternate recipes to make the tool parts out of the molten liquid in the Fluid Solidifier? 

I made this with a Minetweaker script and I think it works very well for GT as it adds a little more difficulty when making tool parts (Dealing with liquids temp etc) since Tinkers is usually quite OP.

If you like the idea, it might be best to make this a config option to add Solidifier recipes (As well as having extruder ones) and make it off by default for the users who like the normal extruder method.

**Comment by Vexatos** [comment]
I'll think about it. I.... I'm not opposed to the idea, but I don't think it's necessary either... I'll see what I can do. If it's possible, it'd only be possible for materials which have a molten equivalent, of course.

**Comment by Muramasa-** [comment]
Thanks, I do really appreciate that you're looking into it.

I do agree it's not necessary, but it does add the mechanic of dealing with liquids again which is interesting.

Again, thanks for taking the time.
