### ISSUE TITLE
Iguana Tinkers Tweaks

### ISSUE THREAD

**Issue by Drobac** [Vexatos/TinkersGregworks#18]
Was wondering if your mod is compatible with Iguana Tinker Tweaks as to have the ability to replace existing tool parts with Tinkers Gregworks parts.
Also when added together, you can adjust TGregworks materials in the Iguana Tweaks config. Would your config and Iguana works together and how do they interact?

**Comment by Vexatos** [comment]
Tool part replacing should work just fine. Regarding the configs, no idea. Try it.
