### ISSUE TITLE
Can repair GT Tico Tools only with Shards

### ISSUE THREAD

**Issue by Dream-Master** [Vexatos/TinkersGregworks#19]
I try to repair Tinkers tools with GT Material but i can't.
Using Version 1.0.8

(Tested with Osmiridium, Electrum)
https://www.dropbox.com/s/n2j9js07ucojl8y/Screenshot%202016-03-15%2017.58.39.png?dl=0

https://www.dropbox.com/s/49zbw7uorjsp8f1/Screenshot%202016-03-15%2017.58.43.png?dl=0

**Comment by Dream-Master** [comment]
Shards seems to work. Is this international?

https://www.dropbox.com/s/3h1bvhci5t659uk/Screenshot%202016-03-15%2018.10.27.png?dl=0

**Comment by Vexatos** [comment]
Indeed. You can only repair it with shards. I can't quite recall why I didn't add a repair recipe for ingots, but I think I thought about it and encountered some limitation in Tinkers' Construct.
I'll close this as it's a bug report but feel free to open another issue so I can look into adding support for ingot repair.
