### ISSUE TITLE
Support Vanilla Tinkers

### ISSUE THREAD

**Issue by Muramasa-** [Vexatos/TinkersGregworks#22]
The method "doesMaterialExist" in TGregRegistery always checks if the material exists in tinkers already. Can we get a config option to ignore if the material is in tinkers so we get GT steel tool parts etc.

On top of this can we get support for vanilla tinkers tool part recipes in GT machines?

**Comment by Vexatos** [comment]
> Can we get a config option to ignore if the material is in tinkers so we get GT steel tool parts etc.

Already there. Added in 1.0.8. `general`.`addMaterialsAnyway`

> On top of this can we get support for vanilla tinkers tool part recipes in GT machines?

Only TCon would be weird if I didn't support every single addon, too. And I'd like not to have to support every single addon. Furthermore, TCon materials pretty much completely overpower TGregworks materials on default config options so I guess it'd be better to just disable them, although I won't ever enforce that, of course.

**Comment by Muramasa-** [comment]
I'm talking about this line:
return !addMaterialsAnyway || TConstructRegistry.toolMaterialStrings.containsKey(m.name());

Even if you set addMaterialsAnyway to true in the config, any mat that exists in tinkers doesn't get added.

I understand you don't want to support every Tinkers addon, but I think supporting tinkers itself it important. There is only 4 materials that need supported.

**Comment by Vexatos** [comment]
I am pretty sure I tested the config option and it worked.

**Comment by Vexatos** [comment]
Okay, that was a derp on my end.

I am pretty sure that [GregTech 5 Unofficial added TCon items to their Materials list](https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/enums/Materials.java#L578-L579). According to this, it also has the correct tag set for TGregworks to recognize it as a tool material. Is that sufficient?

**Comment by Muramasa-** [comment]
Yes that would be sufficient, thanks

**Comment by Vexatos** [comment]
I guess I'll try to release 1.0.10 soon.
Considering this issue resolved.

**Comment by Vexatos** [comment]
1.0.10 is released. Please test the config option.

**Comment by Dream-Master** [comment]
Now two steel Axe Heads are available. One from Tinkers and one from you.

![image](https://cloud.githubusercontent.com/assets/2970688/14142911/c067d73a-f688-11e5-876b-92f11f31f61f.png)

**Comment by Dream-Master** [comment]
Try to upgrade Tinkers Iron Pickaxe with a osmium Pickaxe Head not working too.
![image](https://cloud.githubusercontent.com/assets/2970688/14143025/442280fc-f689-11e5-9f99-e0e91e1b4f42.png)

Try to upgrade a Ignis Pigaxe from TGregworks with a Osmium  Pickaxe Head not works too
![image](https://cloud.githubusercontent.com/assets/2970688/14143049/67fe4a7e-f689-11e5-9ebc-5811ec71c3e7.png)

**Comment by Vexatos** [comment]
@Dream-Master See #23.

**Comment by Dream-Master** [comment]
Yes sorry open it but forgot about it.
