### ISSUE TITLE
Upgrade Tinkers Tool with GT material Parts

### ISSUE THREAD

**Issue by Dream-Master** [Vexatos/TinkersGregworks#23]
One player on my server want to upgrade his Iron Pickaxe to a Stainless Steel  today but it not works.

Upgrading it to steel works withou any problems.

I gusee it is impossible to update Native Tinkers Tools with GT material parts or did we something wrong?

**Comment by mrgreenacid** [comment]
Player here, bit of a clarification. The tool upgrading that iguana's tweaks doesn't seem to work if you want to upgrade with a tinkers' gregworks part.

**Comment by Vexatos** [comment]
Hmm... I do have a custom handler to set the TGw tool part colours correctly. I am probably not expecting the tool part to ever change and thus never re-set the colour when the tool part is swapped, and I am not sure if I am able to detect the removal of a TGw tool. I will look into it once I am back from vacation.

**Comment by OneEyeMaker** [comment]
@Vexatos 
If I understand correctly, [this](https://github.com/SlimeKnights/IguanaTweaksTConstruct/blob/master/src/main/java/iguanaman/iguanatweakstconstruct/replacing/ModPartReplacement.java) class allows to swap tool parts.

If so, you can clone this repository to your machine and add debug code in each point, where [this](https://github.com/SlimeKnights/IguanaTweaksTConstruct/blob/master/src/main/java/iguanaman/iguanatweakstconstruct/replacing/ModPartReplacement.java#L35) function returns ```false```. After it you can run TGreg and modified IguanaTConTweaks and try to swap tool parts in TCon's tools.
At some point you'll find *what* causes this bug (=*at which point* function ```canModify()``` returns false.).

P. S. Sorry for my English. I'm from Russia.

**Comment by Vexatos** [comment]
@OneEyeMaker The issue is [this line](https://github.com/SlimeKnights/IguanaTweaksTConstruct/blob/master/src/main/java/iguanaman/iguanatweakstconstruct/replacing/ModPartReplacement.java#L66). There are two recipes per tool: One normal TCon recipe and one TGregworks recipe. However, ITT only uses the one by TCon and ignores any TGw tool recipe, that's why it doesn't work.

**Comment by Vexatos** [comment]
Fixed the colour being messed up when replacing TGregworks tool parts with normal tool parts. Mind that this only works on tools crafted after this fix. Tools already there will still have their colour broken.

**Comment by Vexatos** [comment]
Well, it should be all fixed now. Version 1.0.12 is released, go give it a try.
