### ISSUE TITLE
Some conflicts with Iguana's TiCon Tweaks.

### ISSUE THREAD

**Issue by OneEyeMaker** [Vexatos/TinkersGregworks#25]
Hello!
I noticed, that Iguana's TiCon Tweaks changes stats of material from TGregworks, if one replaces the same from TiCon (It occurs only when "addMaterialsAnyway" is enabled).
I guess, that adding "before"/"arter" flag for this mod in dependencies list in "@Mod" annotation can resolve this problem.
P. S. Sorry for my English, I'm from Russia.

**Comment by Vexatos** [comment]
I am assuming you have tested this with version 1.0.10?
So with `addMaterialsAnyway`, it modifies TGregworks iron, steel etc. tools (pretty much every tool material TCon itself adds)?
I may be able to circumvent this, I'll look into it once I am back from vacation. I can't guarantee a fix because IguanaTinkerTweaks isn't being worked on for Minecraft 1.7.10 anymore.

**Comment by Vexatos** [comment]
Hmm... Which part of the ITT config is about those stats? The global durability modifiers for instance apply to all tools anyway. The overrides in particular are intended to do this, and I can't see any other place in the config file about that.

**Comment by OneEyeMaker** [comment]
This problem occurs only when there are enabled such modules as "Override", "HarvestLevelTweaks" (I apologise). 
//(I tried to change harvest level of some blocks using this modules, but I found much simplier way to do this).
Only with "Override" module enabled (with "HarvestLevelTweaks") I haven't this bug.

I noticed, that in config file I have only **_one_** variant of each material. that registered by TCon and TGreg (in other words, 2 *real* materials transforms into one material in config, because ITT uses name of material instead of ID).

I can say, that ITT exactly overrides durability and mining speed of material.
Other stats of materials are result of mixing TCon's stats and TGreg's stats:
```
    cobalt {
        I:attack=3
        S:color=dark_aqua
        I:durability=800 //TCon
        D:handleModifier=1.75 //TGreg
        I:harvestLevel=4
        I:miningSpeed=1400
        I:reinforced=2
        D:shoddy=0.0
        D:xpAmount=1.0
    }
    bronze {
        I:attack=2
        S:color=gold
        I:durability=550 //TCon
        D:handleModifier=1.2999999523162842
        I:harvestLevel=2
        I:miningSpeed=800
        I:reinforced=1
        D:shoddy=0.0
        D:xpAmount=1.0
    }
```

**Comment by Vexatos** [comment]
Yes, that is because both materials have the exact same name (otherwise it would be added even without `addMaterialsAnyway`). There is nothing I can do about this. It's... working as intended, I guess.

**Comment by OneEyeMaker** [comment]
OK. In addition, I found another way to solve my problem with block's harvest levels.
