### ISSUE TITLE
Can't repair tools from materials, that both TCon and TGreg add.

### ISSUE THREAD

**Issue by OneEyeMaker** [Vexatos/TinkersGregworks#26]
Title says it all. Tools from TGreg, main part of which (*"head"*) made from materials, such as bronze or cobalt, are unrepairable.
I guess, problem is the same - "get material by name" instead of "get material by ID".

**Comment by Vexatos** [comment]
But... [I register the repair materials by ID...](https://github.com/Vexatos/TinkersGregworks/blob/master/src/main/java/vexatos/tgregworks/integration/TGregRecipeRegistry.java#L188). I have no clue why it wouldn't work. What exactly were you trying to repair them with?

**Comment by OneEyeMaker** [comment]
http://imgur.com/a/UJEJj
The same situation with *any* instruments from these materials.

**Comment by OneEyeMaker** [comment]
You get material by ID, but you use **name**, when you register recipe.
https://github.com/Vexatos/TinkersGregworks/blob/master/src/main/java/vexatos/tgregworks/integration/TGregRecipeRegistry.java#L193

**Comment by Vexatos** [comment]
Well, I guess I have to add my own tool repair recipe too.

**Comment by OneEyeMaker** [comment]
//May be, at some point you should create new major version, that breaks backward compatibility and readds all materials with names, such as *"GT" + MaterialName* (*GTCobalt*, *GTStainlessSteel* etc.)

**Comment by Vexatos** [comment]
TGregworks 1.0.13 is out now with those fixes. Go give it a try.

**Comment by OneEyeMaker** [comment]
Thank you very much!
