### ISSUE TITLE
[Suggestion] Repairing With Tool Parts

### ISSUE THREAD

**Issue by Muramasa-** [Vexatos/TinkersGregworks#27]
Would it be possible to allow you to repair tools with their "head" tool part instead of using ingots etc.

This would make it more interesting as you could have it so players would need to remake the main "head" part of the tool to repair it.

Lets have an example; Osmium Pickaxe:
if I used this tool until it is broken, I could then remake the "head" part of the tool (which would be the pickaxe head in this case) and then combine that with the broken tool in the forge and it would repair the tool fully.

Bonus Feature:
Have a limited number of times you can repair a tool with the main tool part so if you didn't have repairing with ingots enabled, then you could have finite tinker tools.

I hope these can be looked into,

Thanks.

**Comment by Vexatos** [comment]
Can you do that with TCon tools in general? If not, I don't think it fits into this mod. Not sure.

**Comment by Muramasa-** [comment]
It is not default TCon functionality, and yeah it might make more sense having this as a separate mod.

With that said, it does somewhat make sense to have something like that in a GregTech TCon crossover mod, but I guess that's for you to decide.

If you didn't want to do this in TGreg, would you consider making a small TCon addon to do it?

**Comment by Muramasa-** [comment]
Turns out as it isn't as complicated to do this myself as I thought. It just requires one really small change with TGregworks that ill submit a pull request for.
