### ISSUE TITLE
Can´t Start with Gregtech 6.00

### ISSUE THREAD

**Issue by DoktorAerzt** [Vexatos/TinkersGregworks#30]
Hello Vexatos,

can you please make a build with Gregtech 6.00? 

I can´t make my own one. Every time i get a error cause of OpenComputers. 
Can you please help me?

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not resolve li.cil.oc:OpenComputers:MC1.7.10-1.5.21.41.
  Required by:
      vexatos.tgregworks:TinkersGregworks-gregtech6:1.7.10-1.0.14 > com.gregoriust.gregtech:gregtech_1.7.10:6.02.06
   > Could not GET 'https://libraries.minecraft.net/li/cil/oc/OpenComputers/MC1.7.10-1.5.21.41/OpenComputers-MC1.7.10-1.5.21.41.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Have a nice Day

**Comment by Vexatos** [comment]
I just uploaded a GregTech 6 build [here](http://files.vex.tty.sh/TGregworks/dev/). Mind that it is marked as a dev build since I have yet to find a nice bolt recipe (so right now you cannot craft bolts with TGw parts in them).
