### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dream-Master** [Vexatos/TinkersGregworks#7]
Get this Crash when put your jar in my mod Folder. (version 1.0.2)

https://gist.github.com/Dream-Master/ea8bdacc08c7e21a3320#file-gistfile1-txt

**Comment by Vexatos** [comment]
Apparently Extra Utilities is not checking if a material ID is available before it's adding it. That's an ExU bug.

**Comment by Vexatos** [comment]
Hmm... Apparently there is a config option in ExU to manually change the ID. Set it to something like 10000 and see if that helps.

**Comment by Dream-Master** [comment]
Ok thanks will try it.

**Comment by Dream-Master** [comment]
Ok change it to 1000, 1001 and 1002. works thanks.

**Comment by Dream-Master** [comment]
One question. There are Gt fluids now compatible in the Smeltery or how you get the tool heads?

**Comment by Dream-Master** [comment]
Sorry never mind saw the recipes in the Extruder.

**Comment by Dream-Master** [comment]
So i have now so much variations nice ;-)
Fits very good in my pack because using Thinkers Smeltery for making the the Molt and Extruder Forms in there.
