### ISSUE TITLE
Suggestion More TC integration

### ISSUE THREAD

**Issue by Dream-Master** [Vexatos/TinkersGregworks#9]
Make the other tinkers casts in the extruder available too. (like the shards cast)
And tinkers tool heads and parts in the extruder too.
Using first the tinkers smeltery and later more and more GT machines
I can make it with Minetweaker and my GT Tweaker too but implement this inside your code would be better.

**Comment by Vexatos** [comment]
I won't do that. TCon-specific things should require TCon devices to be crafted. You can always use _Tweaker for that.
